# Userpool
Resources:
  myUsersPool:
    Type: AWS::Cognito::UserPool

# Userpool client
  myUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: myUserPoolClient
      GenerateSecret: false
      UserPoolId: 
        Ref: myUsersPool

# authorizer
  # myAuthorizer:
  #   Type: AWS::ApiGateway::Authorizer
  #   Properties:
  #     Type: COGNITO_USER_POOLS
  #     IdentitySource: method.request.header.Authorization
  #     Name: userAuthorizer2
  #     ProviderARNs: 
  #       - Fn::GetAtt:
  #         - myUsersPool
  #         - Arn
  #     RestApiId: 
  #       Ref: ApiGatewayRestApi