createUser:
  handler: src/createUser/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - sqs:SendMessage
        - sns:Publish
      Resource:
        - Fn::ImportValue: core-service-stack-dev-UserNotifyTopic
        - Fn::GetAtt:
          - MyAppDatabase
          - Arn
  environment:
    USER_POOL: 
      Ref: CognitoUserPool
    USER_POOL_CLIENT: 
      Ref: CognitoUserPoolClient
    TABLE_NAME:
      Ref: MyAppDatabase
    SNS_ARN:
      Fn::ImportValue: core-service-stack-dev-UserNotifyTopic
  events:
    - http:
        method: post
        path: /v1/users

getUser:
  handler: src/getUser/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource:
        Fn::GetAtt:
          - MyAppDatabase
          - Arn
  environment:
    TABLE_NAME:
      Ref:  MyAppDatabase
  events:
    - http:
        method: get
        path: /v1/users

editUser:
  handler: src/editUser/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:UpdateItem
      Resource:
      - Fn::ImportValue: core-service-stack-dev-UserNotifyTopic
      - Fn::GetAtt:
          - MyAppDatabase
          - Arn
  environment:
    SNS_ARN:
      Fn::ImportValue: core-service-stack-dev-UserNotifyTopic
    TABLE_NAME:
      Ref: MyAppDatabase
  events:
    - http:
        method: put
        path: /v1/users
        authorizer: 
          authorizerId: 
            Ref: CognitoAuthorizer
          type: COGNITO_USER_POOLS


uploadProfilePicture:
  handler: src/uploadProfilePicture/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:PutObjectTagging
        - s3:PutBucketAcl
      Resource:
        - Fn::GetAtt:
          - imagesBucket
          - Arn
  environment:
    BUCKET_NAME:
      Ref: imagesBucket
    REGION: 'us-east-1'
  events:
    - http:
        method: post
        path: /v1/upload-profile-picture
        # authorizer: 
        #   type: COGNITO_USER_POOLS
        #   authorizerId: 
        #     Ref: myAuthorizer



# deleteUser:
#   handler: src/users/deleteUser/handler.default
#   iamRoleStatements:
#     - Effect: Allow
#       Action:
#         - dynamodb:DeleteItem
#       Resource:
#         Fn::GetAtt:
#           - MyAppDatabase
#           - Arn
#   environment:
#     TABLE_NAME:
#       Ref:  MyAppDatabase
#   events:
#     - http:
#         method: delete
#         path: /v1/users