Resources:
  emailQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "emailQueue"
      VisibilityTimeout: 30
      
  slackQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "slackQueue"
      VisibilityTimeout: 30