Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: '${self:service}${self:provider.stage}-user-notify'
Outputs:
  MySNSTopicArn:
    Value:
      Ref: MySNSTopic
    Export:
      Name: ${self:service}-${self:provider.stage}-UserNotifyTopic
