sendEmail:
  handler: src/sendEmail/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - Fn::GetAtt:
          - emailQueue2
          - Arn
  environment:
    QUEUE_URL:
      Ref: emailQueue2
  events:
    - sqs:
          arn:
            Fn::GetAtt:
              - emailQueue2
              - Arn    
          batchSize: 10
          maximumBatchingWindow: 60
          functionResponseType: ReportBatchItemFailures

sendSlack:
  handler: src/sendSlack/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - Fn::GetAtt:
          - slackQueue2
          - Arn
  environment:
    QUEUE_URL:
      Ref: slackQueue2
  events:
    - sqs:
          arn:
            Fn::GetAtt:
              - slackQueue2
              - Arn    
          batchSize: 10
          maximumBatchingWindow: 60
          functionResponseType: ReportBatchItemFailures