Resources:
  mySqsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: mySqsQueuePolicy
        Statement:
        - Sid: Allow-sns-SendMessage
          Effect: Allow
          Principal: 
            Service: sns.amazonaws.com
          Action:
          - sqs:SendMessage
          Resource: "*"
          Condition: 
            ArnEquals:
              aws:SourceArn:
              - Fn::ImportValue: core-service-stack-dev-UserNotifyTopic
      Queues:
        - Ref: emailQueue2
        - Ref: slackQueue2