Resources:
  emailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: 
        Fn::GetAtt:
          - MySNSTopic
          - TopicArn
      Endpoint: 
        Fn::GetAtt:
          - emailQueue
          - Arn
      Protocol: sqs
  slackSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: 
        Fn::GetAtt:
          - MySNSTopic
          - TopicArn
      Endpoint: 
        Fn::GetAtt:
          - slackQueue
          - Arn
      Protocol: sqs

      